from __future__ import annotations

import inspect
import json
from typing import Any

from . import synth
from .models import Finding

_HEADER = '''#!/usr/bin/env python3
"""{api}: {oracle} oracle - {kind}

{detail}

Generated by the artifact. Exits 1 while the finding reproduces, 0 once fixed.
"""
import sys

import numpy as np

'''

_FOOTER = '''

API = {api!r}
ARGS = {args!r}
ORACLE = {oracle!r}
KIND = {kind!r}
RECEIVER_PATH = {receiver_path!r}
RECEIVER_ARGS = {receiver_args!r}


def _resolve(path):
    import importlib
    parts = path.split(".")
    obj = importlib.import_module(parts[0])
    idx = 1
    while idx < len(parts):
        candidate = ".".join(parts[: idx + 1])
        try:
            spec = importlib.util.find_spec(candidate)
        except (ImportError, ValueError, AttributeError):
            spec = None
        if spec is None:
            break
        obj = importlib.import_module(candidate)
        idx += 1
    for name in parts[idx:]:
        obj = getattr(obj, name)
    return obj


def _native(root, value, dtype_name):
    if root == "numpy" or not isinstance(value, np.ndarray):
        return value
    import importlib
    mod = importlib.import_module(root)
    dtype = getattr(mod, dtype_name, None) if dtype_name else None
    for ctor_name in ("asarray", "array", "tensor", "constant", "from_numpy"):
        ctor = getattr(mod, ctor_name, None)
        if not callable(ctor):
            continue
        for kwargs in ([{{"dtype": dtype}}] if dtype is not None else []) + [{{}}]:
            try:
                return ctor(value, **kwargs)
            except Exception:
                continue
    return value


def _iter_numeric(obj, depth=0):
    if depth > 3 or obj is None or isinstance(obj, (bool, np.bool_)):
        return
    if isinstance(obj, (int, float, np.integer, np.floating, complex)):
        yield np.asarray(obj)
        return
    if isinstance(obj, np.ndarray):
        if obj.dtype.kind in "fc":
            yield obj
        return
    if isinstance(obj, (list, tuple)):
        for item in list(obj)[:8]:
            yield from _iter_numeric(item, depth + 1)
        return
    for attr in ("detach", "cpu", "numpy", "asnumpy", "__array__"):
        fn = getattr(obj, attr, None)
        if callable(fn):
            try:
                converted = fn()
            except Exception:
                continue
            if isinstance(converted, np.ndarray):
                if converted.dtype.kind in "fc":
                    yield converted
                return
            if converted is not obj:
                yield from _iter_numeric(converted, depth + 1)
                return


def _build_args(entries, root):
    positional, keyword = [], {{}}
    for entry in entries:
        recipe = entry["recipe"] or {{}}
        if recipe.get("form") == "receiver":
            value = _build_receiver(recipe.get("path", RECEIVER_PATH),
                                    list(recipe.get("args", {{}}).values()), root)
        else:
            value = _native(root, build_value(recipe) if recipe else None,
                            entry.get("dtype"))
        if entry["by_keyword"]:
            keyword[entry["name"]] = value
        else:
            positional.append(value)
    return positional, keyword


def _build_receiver(path, described_args, root):
    cls = _resolve(path)
    entries = [{{"name": d.get("name", ""), "recipe": d.get("recipe") or {{}},
                "dtype": d.get("dtype"), "by_keyword": bool(d.get("by_keyword"))}}
               for d in described_args if not d.get("omitted")]
    positional, keyword = _build_args(entries, root)
    try:
        return cls(*positional, **keyword)
    except Exception:
        return cls()


def main() -> int:
    root = API.split(".", 1)[0]
    positional, keyword = _build_args(ARGS, root)

    if RECEIVER_PATH:
        instance = _build_receiver(RECEIVER_PATH, RECEIVER_ARGS, root)
        fn = getattr(instance, API.rsplit(".", 1)[1])
        print(f"receiver: {{RECEIVER_PATH}} -> {{instance!r}}"[:200])
    else:
        fn = _resolve(API)

    print(f"calling {{API}} with {{len(positional)}} positional and {{sorted(keyword)}} keyword args")
    if ORACLE == "crash":
        result = fn(*positional, **keyword)     # a crash/hang kills the process here
        print("no crash: call returned", type(result).__name__)
        return 0

    result = fn(*positional, **keyword)
    for arr in _iter_numeric(result):
        if arr.size and not np.all(np.isfinite(arr)):
            flat = np.asarray(arr).ravel()
            bad = flat[~np.isfinite(flat)]
            print(f"BUG REPRODUCES: {{API}} returned {{bad.size}} non-finite value(s) "
                  f"for finite inputs, e.g. {{[float(v) for v in bad[:3]]}}")
            return 1
    print("OK: output is finite")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def _entries(order: list[str], args: dict[str, Any]) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for name in order:
        described = args.get(name)
        if not described or described.get("omitted"):
            continue
        entries.append({
            "name": name,
            "recipe": described.get("recipe") or {},
            "dtype": described.get("dtype"),
            "by_keyword": bool(described.get("by_keyword")),
        })
    return entries


def _arg_entries(finding: Finding) -> list[dict[str, Any]]:
    return _entries(finding.order, finding.args)


def _receiver_entries(finding: Finding) -> list[dict[str, Any]]:
    return _entries(finding.receiver_order, finding.receiver_args)


def render(finding: Finding) -> str:
    body = inspect.getsource(synth).lstrip("\n")
    body = body.replace("from __future__ import annotations\n", "")
    body = body.replace("import numpy as np\n", "")
    header = _HEADER.format(api=finding.api, oracle=finding.oracle,
                            kind=finding.kind, detail=finding.detail.strip()[:600])
    footer = _FOOTER.format(api=finding.api, args=_arg_entries(finding),
                            oracle=finding.oracle, kind=finding.kind,
                            receiver_path=finding.receiver_path,
                            receiver_args=_receiver_entries(finding)
                            if finding.receiver_path else [])
    return header + body + footer


def write(finding: Finding, path: str) -> None:
    with open(path, "w") as handle:
        handle.write(render(finding))


def slug(api: str, index: int) -> str:
    return f"{api.replace('.', '_')}__{index:03d}.py"


def dump_finding(finding: Finding, path: str) -> None:
    with open(path, "w") as handle:
        json.dump(finding.to_json(), handle, indent=2, default=repr)
